adminUser:
  password: vault:jx-aps-glassboom/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-glassboom:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-glassboom:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-glassboom/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-glassboom/prow:hmacToken
